name: E2E Tests

on:
  pull_request:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'

      - name: Install kind
        run: |
          curl -Lo kind https://kind.sigs.k8s.io/dl/v0.20.0/kind-linux-amd64
          chmod +x kind
          sudo mv kind /usr/local/bin/

      - name: Install kubectl
        run: |
         curl -Lo kubectl https://dl.k8s.io/release/v1.30.0/bin/linux/amd64/kubectl
         chmod +x kubectl
         sudo mv kubectl /usr/local/bin/

      - name: Create kind cluster with custom config
        run: |
          mkdir -p $HOME/.kube
          kind create cluster \
            --config=examples/kind/kind-config.yaml \
            --name test-cluster \
            --kubeconfig=$HOME/.kube/config

      - name: Install Ginkgo CLI
        run: |
          go install github.com/onsi/ginkgo/v2/ginkgo@latest
        env:
          GOBIN: ${{ github.workspace }}/bin

      - name: Add ginkgo to PATH
        run: echo "${{ github.workspace }}/bin" >> $GITHUB_PATH

      - name: Tidy Go Modules
        run: go mod tidy
        working-directory: ${{ github.workspace }}

      - name: Run E2E tests
        run: make test-e2e

      - name: Delete kind cluster
        if: always()
        run: kind delete cluster --name test-cluster
